#!/bin/bash
# Helper script to build verovio toolkit before building Neon

pushd verovio/emscripten
sed -i '' 's/-O3/-Os/' buildToolkit
./buildToolkit -x "Gootville,Leipzig,Petaluma" -DHPX
./buildToolkit -x "Gootville,Leipzig,Petaluma" -DHPX -w
sed -i '' 's/-Os/-O3/' buildToolkit
cp build/verovio-toolkit-wasm.js build/verovio.wasm ../../public/
popd
